// Shaker — shared data & tokens

const SHAKER = {
  // Palette (Purchasely-inspired)
  indigo:      '#3C4876',
  indigoDark:  '#2A3358',
  indigoSoft:  '#E4E6F3',
  accent:      '#2B79E4',
  accentDark:  '#1E5EB8',
  danger:      '#D33A3A',
  gold:        '#F5B93A',
  goldSoft:    '#FFF4D9',
  orange:      '#E8723F',
  green:       '#23C071',
  bgLight:     '#F3F1F9',
  bgCard:      '#FFFFFF',
  textPrimary: '#1C1E2C',
  textSec:     '#6A6F88',
  textTer:     '#9EA2B6',
  hair:        'rgba(60,72,118,0.12)',

  // Dark
  bgDark:      '#0F1020',
  bgDarkCard:  '#1B1D30',
  textDark:    '#F4F3FB',
  textDarkSec: '#9EA2B6',
  hairDark:    'rgba(255,255,255,0.08)',
};

// ─────────────────────────────────────────────────────────────
// Cocktail catalog — small subset
// ─────────────────────────────────────────────────────────────
const COCKTAILS = [
  { id: 'virgin-mojito', name: 'Virgin Mojito', cat: 'Non-alcoholic', diff: 'Easy', spirit: 'None',
    hue: 120, glass: 'highball', tint1: '#C7F0C8', tint2: '#7CCB8F', garnish: 'mint',
    blurb: 'All the refreshing lime-and-mint magic of a classic Mojito, without the rum.',
    ingredients: ['Fresh lime juice', 'Sugar syrup', 'Mint leaves', 'Soda water', 'Crushed ice'],
    steps: ['Muddle mint leaves gently with sugar syrup in a tall glass.', 'Add lime juice and fill with crushed ice.', 'Top with soda water and stir.', 'Garnish with a mint sprig and lime wheel.'],
    premium: false },
  { id: 'shirley-temple', name: 'Shirley Temple', cat: 'Non-alcoholic', diff: 'Easy', spirit: 'None',
    hue: 350, glass: 'highball', tint1: '#FDD2D8', tint2: '#EF6C7A', garnish: 'cherry',
    blurb: 'A bubbly pink classic that made every kid feel fancy at the grown-ups\u2019 table.',
    ingredients: ['Ginger ale', 'Grenadine', 'Maraschino cherry', 'Orange slice', 'Crushed ice'],
    steps: ['Fill a highball with ice.', 'Add grenadine.', 'Top with ginger ale.', 'Garnish with cherry and orange.'],
    premium: false },
  { id: 'pina-colada', name: 'Piña Colada', cat: 'Tropical', diff: 'Medium', spirit: 'Rum',
    hue: 48, glass: 'highball', tint1: '#FFF1C4', tint2: '#F2C061', garnish: 'pineapple',
    blurb: 'Coconut cream, pineapple, white rum — if you like getting caught in the rain.',
    ingredients: ['White rum', 'Coconut cream', 'Pineapple juice', 'Crushed ice', 'Pineapple wedge'],
    steps: ['Blend rum, coconut cream, juice with ice.', 'Pour into a hurricane glass.', 'Garnish with pineapple wedge and cherry.'],
    premium: true },
  { id: 'manhattan', name: 'Manhattan', cat: 'Classic', diff: 'Easy', spirit: 'Whiskey',
    hue: 28, glass: 'martini', tint1: '#E6B278', tint2: '#8E4A1E', garnish: 'orange',
    blurb: 'A sophisticated whiskey cocktail that\u2019s stood the test of time since the 1870s.',
    ingredients: ['Rye whiskey', 'Sweet vermouth', 'Angostura bitters', 'Maraschino cherry'],
    steps: ['Stir whiskey, vermouth and bitters in a mixing glass with ice.', 'Strain into a chilled coupe.', 'Garnish with a cherry or orange twist.'],
    premium: true },
  { id: 'espresso-martini', name: 'Espresso Martini', cat: 'Contemporary', diff: 'Medium', spirit: 'Vodka',
    hue: 25, glass: 'martini', tint1: '#C9A27A', tint2: '#3B2416', garnish: 'beans',
    blurb: 'Cold coffee, cold vodka, and the only espresso you\u2019ll drink after 9pm.',
    ingredients: ['Vodka', 'Fresh espresso', 'Coffee liqueur', 'Sugar syrup'],
    steps: ['Shake all ingredients hard with ice.', 'Double strain into a chilled coupe.', 'Float three coffee beans.'],
    premium: true },
  { id: 'negroni', name: 'Negroni', cat: 'Classic', diff: 'Easy', spirit: 'Gin',
    hue: 5, glass: 'rocks', tint1: '#E98672', tint2: '#9A2E1C', garnish: 'orange',
    blurb: 'Equal parts gin, Campari, sweet vermouth. Bitter, red, perfect.',
    ingredients: ['Gin', 'Campari', 'Sweet vermouth', 'Orange peel'],
    steps: ['Stir all in a mixing glass with ice.', 'Strain over a big cube in a rocks glass.', 'Express orange peel and drop in.'],
    premium: true },
  { id: 'daiquiri', name: 'Daiquiri', cat: 'Classic', diff: 'Easy', spirit: 'Rum',
    hue: 55, glass: 'martini', tint1: '#F4F0CC', tint2: '#C7B970', garnish: 'lime',
    blurb: 'Three ingredients. Shaken, not stirred. Hemingway-approved.',
    ingredients: ['White rum', 'Fresh lime juice', 'Sugar syrup'],
    steps: ['Shake all with ice.', 'Double strain into a chilled coupe.', 'Garnish with a lime wheel.'],
    premium: true },
  { id: 'margarita', name: 'Margarita', cat: 'Classic', diff: 'Easy', spirit: 'Tequila',
    hue: 68, glass: 'coupe', tint1: '#E4F2B8', tint2: '#9CB949', garnish: 'lime',
    blurb: 'Tequila, lime, triple sec — rimmed with salt, ready for sunshine.',
    ingredients: ['Blanco tequila', 'Triple sec', 'Fresh lime juice', 'Salt'],
    steps: ['Rim a coupe with salt.', 'Shake all ingredients with ice.', 'Strain into the coupe and garnish with lime.'],
    premium: true },
];

Object.assign(window, { SHAKER, COCKTAILS });
